create table
  public.shelves (
    id bigint generated by default as identity,
    name text not null,
    zone bigint not null,
    warehouse bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint shelf_items_pkey primary key (id),
    constraint shelf_items_name_key unique (name),
    constraint shelf_items_warehouse_fkey foreign key (warehouse) references warehouses (id)
  ) tablespace pg_default;

create table
  public.warehouses (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    constraint warehouses_pkey primary key (id)
  ) tablespace pg_default;